In [61]:
#1. 학습률, epoch을 변경하면서 정답이 나오도록 조절 
import numpy as np
InputLayerSize, hiddenLayerSize, outputLayerSize = 2, 3, 1

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0],[1],[1],[0]])

def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_diff(x):
    return x*(1-x)


#hidden_Weights = np.random.randn(InputLayerSize, hiddenLayerSize)
hidden_Weights = np.random.uniform(size=(InputLayerSize,hiddenLayerSize))
print("----------------Hidden Layer Weights----------------")
print(hidden_Weights)
print(hidden_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
#Output_Weights = np.random.randn(hiddenLayerSize, outputLayerSize)
Output_Weights = np.random.uniform(size=(hiddenLayerSize,outputLayerSize))
print(Output_Weights)
print(Output_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n")

epochs = int(input("epoch값 입력 : ")) #epoch
L = float(input("Learning rate값 입력 :")) #LR

for i in range(epochs):
    Hidden_result = sigmoid(np.dot(X, hidden_Weights)) #4by2*2by3 -> 4by3
    Output = np.dot(Hidden_result, Output_Weights)     #4by3*3by1 -> 4by1
    Error = Y - Output
    dZ = Error*L
    Output_Weights += Hidden_result.T.dot(dZ)          #3by4*4by1 -> 3by1
    dHidden_result = dZ.dot(Output_Weights.T)*sigmoid_diff(Hidden_result)
    hidden_Weights += X.T.dot(dHidden_result)
m = np.sum(Output)/len(X)
for i in range(len(X)):
    if Output[i][0] < m:
        Output[i][0] = 0
    else:
        Output[i][0] = 1
print("\n XOR 2 inputs")
print(Output)

----------------Hidden Layer Weights----------------
[[0.95234577 0.42064874 0.24043071]
 [0.30834402 0.10701586 0.49858842]]
(2, 3)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[0.93519592]
 [0.12839615]
 [0.94506519]]
(3, 1)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

epoch값 입력 : 100000
Learning rate값 입력 :0.1

 XOR 3 inputs
[[0.]
 [1.]
 [1.]
 [0.]]


In [57]:
#2. 입력이 2인 XOR문제를 입력이 2인 NAND문제로 변경 
import numpy as np
InputLayerSize, hiddenLayerSize, outputLayerSize = 2, 3, 1

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[1],[1],[1],[0]])

def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_diff(x):
    return x*(1-x)


#hidden_Weights = np.random.randn(InputLayerSize, hiddenLayerSize)
hidden_Weights = np.random.uniform(size=(InputLayerSize,hiddenLayerSize))
print("----------------Hidden Layer Weights----------------")
print(hidden_Weights)
print(hidden_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
#Output_Weights = np.random.randn(hiddenLayerSize, outputLayerSize)
Output_Weights = np.random.uniform(size=(hiddenLayerSize,outputLayerSize))
print(Output_Weights)
print(Output_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n")

epochs = int(input("epoch값 입력 : ")) #epoch
L = float(input("Learning rate값 입력 :")) #LR

for i in range(epochs):
    Hidden_result = sigmoid(np.dot(X, hidden_Weights)) #4by2*2by3 -> 4by3
    Output = np.dot(Hidden_result, Output_Weights)     #4by3*3by1 -> 4by1
    Error = Y - Output
    dZ = Error*L
    Output_Weights += Hidden_result.T.dot(dZ)          #3by4*4by1 -> 3by1
    dHidden_result = dZ.dot(Output_Weights.T)*sigmoid_diff(Hidden_result)
    hidden_Weights += X.T.dot(dHidden_result)

m = np.sum(Output)/len(X)
for i in range(len(X)):
    if Output[i][0] < m:
        Output[i][0] = 0
    else:
        Output[i][0] = 1
print("\n NAND 2 inputs")
print(Output)    


----------------Hidden Layer Weights----------------
[[0.57142929 0.72248317 0.42377372]
 [0.75229924 0.77834837 0.57598257]]
(2, 3)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[0.66561389]
 [0.18881768]
 [0.85779416]]
(3, 1)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

epoch값 입력 : 10000
Learning rate값 입력 :0.1

 NAND 2 inputs
[[1.]
 [1.]
 [1.]
 [0.]]


In [55]:
#3. 입력이 3인 XOR문제로 변경 
import numpy as np
InputLayerSize, hiddenLayerSize, outputLayerSize = 3, 5, 1

X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0]
             , [1, 1, 1]]) 
Y = np.array([[0], [1], [1], [0], [1], [0], [0], [1]])
#x : 8by3
#y : 8by1
def sigmoid(x):
    return 1/(1+np.exp(-x))
def sigmoid_diff(x):
    return x*(1-x)


#hidden_Weights = np.random.randn(InputLayerSize, hiddenLayerSize)
hidden_Weights = np.random.uniform(size=(InputLayerSize,hiddenLayerSize))
print("----------------Hidden Layer Weights----------------")
print(hidden_Weights)
print(hidden_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
#Output_Weights = np.random.randn(hiddenLayerSize, outputLayerSize)
Output_Weights = np.random.uniform(size=(hiddenLayerSize,outputLayerSize))
print(Output_Weights)
print(Output_Weights.shape)
print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

epochs = int(input("epochs값 입력 : ")) #epoch
L = float(input("Learning rate값 입력 :")) #LR

for i in range(epochs):
    Hidden_result = sigmoid(np.dot(X, hidden_Weights)) 
    Output = np.dot(Hidden_result, Output_Weights)     
    Error = Y - Output
    dZ = Error*L
    Output_Weights += Hidden_result.T.dot(dZ)          
    dHidden_result = dZ.dot(Output_Weights.T)*sigmoid_diff(Hidden_result)
    hidden_Weights += X.T.dot(dHidden_result)

m = np.sum(Output)/len(X)
for i in range(len(X)):
    if Output[i][0] < m:
        Output[i][0] = 0
    else:
        Output[i][0] = 1
print("\n XOR 3 inputs")
print(Output)

----------------Hidden Layer Weights----------------
[[0.38682531 0.45684023 0.03546715 0.35679047 0.72861493]
 [0.63145798 0.39350406 0.391156   0.91129659 0.11400244]
 [0.28905902 0.08472648 0.26402322 0.72226402 0.68839159]]
(3, 5)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[0.49718595]
 [0.06925891]
 [0.22550945]
 [0.16898598]
 [0.62524872]]
(5, 1)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
epochs값 입력 : 100000
Learning rate값 입력 :0.01

 XOR 3 inputs
[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]]


In [ ]:
print("1")